### ISSUE TITLE
extracting temperatures should be done when printing a line, not when appending it

### ISSUE THREAD

**Issue by woutgg** [Doodle3D/print3d#12]
Waiting with extracting until the gcode line is actually being sent to the printer would result in more accurate target temperatures.

**Comment by peteruithoven** [comment]
When an `ok` is received `sendCode` is called, which calls [`extractGCodeInfo`](https://github.com/Doodle3D/print3d/blob/master/src/drivers/MarlinDriver.cpp#L305:L325), which actually checks for heatup commands (`M109`, `M104`, `M190`, `M140`). So I think we've implemented this. 

It's also called by `appendGCode`, which is a bit weird...
