### ISSUE TITLE
Set total lines manually

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/print3d#31]
Currently the `total_lines` is probably `buffered_lines` + `current_line`, but this means that while still sending (buffering) gcode total_lines is far of the actual total lines. 
It would be interesting to allow overriding this in the `/printer/print` api request.

**Comment by woutgg** [comment]
Implemented (see https://github.com/Doodle3D/doodle3d-firmware/issues/51#issuecomment-198393165 for details).
