### ISSUE TITLE
invalid option -- V

### ISSUE THREAD

**Issue by peteruithoven** [Doodle3D/print3d#37]
In the `feature/logging+checking-renewed` branch, when I change the log level in the Settings popup in the client to Bulk print3d just logs: 
```
/bin/print3d: invalid option -- V
```
The V option doesn't seem to exist in print3d anymore, maybe the shell scripts need to be updated? Like:
https://github.com/Doodle3D/print3d/blob/feature/logging%2Bchecking-renewed/src/script/print3d-runner.sh#L10-L18
Does print3d get it's loglevel from uci automatically? Shouldn't the `-u` option be passed?

**Comment by woutgg** [comment]
Fixed in 4c43f11f6695b4712ecd97baf5c60422d21163d0.
